sonata_admin:
    title: 'ISABEE-UEB'
    show_mosaic_button: false
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    options:
        # Choices are: text, icon or all (default)
        list_action_button_content: icon

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]